name: Client

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Get Packages
      shell: bash
      working-directory: ${{github.workspace}}/HorusClient
      run: go get -v
      
    - name: Build client
      shell: bash
      working-directory: ${{github.workspace}}/HorusClient
      run: go build -v
