name: MQServer Build

on: push

jobs:
  build:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Get Packages
      shell: bash
      working-directory: ${{github.workspace}}/MQServer
      run: go get -v
      
    - name: Build server
      shell: bash
      working-directory: ${{github.workspace}}/MQServer
      run: go build -v
